=== NabinGrz/Website_From_XML-Sound-Soul-/catalog_19031160.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="MusicStore" type="MusicStoreType">
  </xs:element>
  <xs:complexType name="websiteaddressType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="web"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="telephoneno2Type">
    <xs:simpleContent>
      <xs:extension base="xs:long">
        <xs:attribute type="xs:string" name="tel_id"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="songdetailType">
    <xs:sequence>
      <xs:element type="genreType" name="genre" minOccurs="0">
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:string" name="songid" use="optional"/>
  </xs:complexType>
  <xs:complexType name="blueType">
    <xs:sequence>
      <xs:element type="xs:string" name="offers"/>
      <xs:element type="xs:string" name="buynow"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="contactType">
    <xs:sequence>
      <xs:element type="xs:string" name="link"/>
      <xs:element type="addressType" name="address"/>
      <xs:element type="telephonenumberType" name="telephonenumber"/>
      <xs:element type="websiteaddressType" name="websiteaddress"/>
      <xs:element type="noteType" name="note"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="c_id"/>
  </xs:complexType>
  <xs:complexType name="countryType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="dtl"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="dtlType">
    <xs:sequence>
      <xs:element type="xs:string" name="year"/>
      <xs:element type="xs:string" name="month" minOccurs="0"/>
      <xs:element type="xs:byte" name="day" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="noofartistsType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:byte" name="dtl"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="featbyType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="dtl"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="genreType">
    <xs:sequence>
      <xs:element type="xs:string" name="songname"/>
      <xs:element type="genrenameType" name="genrename"/>
      <xs:element type="countryType" name="country"/>
      <xs:element type="directornameType" name="directorname" minOccurs="0"/>
      <xs:element type="producerType" name="producer"/>
      <xs:element type="writerType" name="writer"/>
      <xs:element type="singersType" name="singers"/>
      <xs:element type="featbyType" name="featby" minOccurs="0"/>
      <xs:element type="noofartistsType" name="noofartists" minOccurs="0"/>
      <xs:element type="releaseyearType" name="releaseyear"/>
      <xs:element type="songlengthType" name="songlength"/>
      <xs:element type="albumType" name="album" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="genre_name" use="optional"/>
    <xs:attribute type="xs:string" name="genre_id" use="optional"/>
  </xs:complexType>
  <xs:complexType name="MusicStoreType">
    <xs:sequence>
      <xs:element type="blueType" name="blue"/>
      <xs:element type="xs:string" name="pattern"/>
      <xs:element type="xs:string" name="slogan"/>
      <xs:element type="storeinfoType" name="storeinfo"/>
      <xs:element type="songsType" name="songs"/>
      <xs:element type="contactType" name="contact"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="genrenameType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="dtl"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="songsType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="xs:string" name="img1"/>
      <xs:element type="songdetailType" name="songdetail"/>
      <xs:element name="img13">
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:element type="genreType" name="genre" minOccurs="0">
            </xs:element>
          </xs:sequence>
          <xs:attribute type="xs:string" name="songid" use="optional"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="img3">
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:element type="genreType" name="genre" minOccurs="0">
            </xs:element>
          </xs:sequence>
          <xs:attribute type="xs:string" name="songid" use="optional"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="img5">
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:element type="genreType" name="genre" minOccurs="0">
            </xs:element>
          </xs:sequence>
          <xs:attribute type="xs:string" name="songid" use="optional"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="img4">
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:element type="genreType" name="genre" minOccurs="0">
            </xs:element>
          </xs:sequence>
          <xs:attribute type="xs:string" name="songid" use="optional"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="img6">
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:element type="genreType" name="genre" minOccurs="0">
            </xs:element>
          </xs:sequence>
          <xs:attribute type="xs:string" name="songid" use="optional"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="img7">
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:element type="genreType" name="genre" minOccurs="0">
            </xs:element>
          </xs:sequence>
          <xs:attribute type="xs:string" name="songid" use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="albumType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="dtl"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="telephoneno3Type">
    <xs:simpleContent>
      <xs:extension base="xs:long">
        <xs:attribute type="xs:string" name="tel_id"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="writerType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="dtl"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="addressType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="con"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="ad"/>
  </xs:complexType>
  <xs:complexType name="singersType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="dtl"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="songlengthType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="dtl"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="releaseyearType" mixed="true">
    <xs:sequence>
      <xs:element type="dtlType" name="dtl"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="producerType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="dtl"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="noteType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="note_id"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="telephoneno1Type">
    <xs:simpleContent>
      <xs:extension base="xs:long">
        <xs:attribute type="xs:string" name="tel_id"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="telephonenumberType" mixed="true">
    <xs:sequence>
      <xs:element type="telephoneno1Type" name="telephoneno1"/>
      <xs:element type="telephoneno2Type" name="telephoneno2"/>
      <xs:element type="telephoneno3Type" name="telephoneno3"/>
      <xs:element type="xs:string" name="telephoneno4"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="tel_phone"/>
  </xs:complexType>
  <xs:complexType name="directornameType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="dtl"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="storeinfoType">
    <xs:sequence>
      <xs:element type="xs:string" name="logo"/>
      <xs:element type="xs:string" name="storename"/>
      <xs:element type="xs:string" name="aboutstore"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="store"/>
  </xs:complexType>
</xs:schema>

=== NabinGrz/Website_From_XML-Sound-Soul-/catalog_19031160.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="catalog_19031160.css"?>
<!DOCTYPE MusicStore SYSTEM "19031160.dtd">
<!-- xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="catalog_19031160.xsd" -->
<MusicStore>
	<blue>
		<offers>Get 1 music free on 2 purchase. SUBSCRIBE <![CDATA[&]]> SAVE 20%</offers>
		<buynow/>
	</blue>
	<pattern/>
	<slogan>Music is the mediator between the spiritual and the sensual life.</slogan>
	<storeinfo store="S1">
		<logo/>
		<storename>Sound Soul</storename>
		<aboutstore><![CDATA[Sound Soul is a full-fledged online musical instruments store that sells all kinds of musics,musical instruments & related equipment & accessories in US.We proudly deal in the best musical instruments, accessories & studio recording equipments.We are also committed to help the musicians by providng them a music class from best teachers. We were among the earliest catalog marketers of music gear & the first to focus on rock-band gear, so we experienced amazingly rapid growth.]]></aboutstore>
	</storeinfo>
	<songs>
		<img1/>
		<songdetail songid="SID1">
			<!--genre_id required-->
			<genre genre_name="rock" genre_id="r1">
				<songname>Nothing Else Matters</songname>
				<genrename>Genre: <dtl>Rock</dtl></genrename>
				<country> Country: <dtl>US</dtl></country>
				<producer> Producer:  <dtl>Lars Ulrich</dtl>	</producer>
				<writer>  Writer:   <dtl>James Hetfield</dtl></writer>
				<singers>Singers: <dtl>James Hetfield</dtl></singers>
				<noofartists> No of Artists: <dtl>4</dtl></noofartists>
				<releaseyear>Release Year: <dtl><year>1992/</year></dtl></releaseyear>
				<songlength> Song Length:  <dtl>6:28</dtl></songlength>
			</genre>
		</songdetail>
		<img13/>
		<songdetail songid="SID2">
			<genre genre_name="pop" genre_id="p1">
				<songname>7 rings</songname>
				<genrename>
               Genre:
               <dtl>Pop</dtl>
				</genrename>
				<country>
               Country:
               <dtl>UK</dtl>
				</country>
				<directorname>
               Director Name:
               <dtl>Hannah Lux Davis</dtl>
				</directorname>
				<producer>
               Producer:
               <dtl>Tommy Brown, Micheal Foster</dtl>
				</producer>
				<writer>
               Writer:
               <dtl>Victoria Monet, Tayla Parx</dtl>
				</writer>
				<singers>
               Singers:
               <dtl>Ariana Grande</dtl>
				</singers>
				<noofartists>
               No of Artists:
               <dtl>1</dtl>
				</noofartists>
				<releaseyear>
               Release Year:
               <dtl>
						<year>2019/</year>
						<month>01/</month>
						<day>18</day>
					</dtl>
				</releaseyear>
				<songlength>
               Song Length:
               <dtl>2:58</dtl>
				</songlength>
				<album>
               Album Name:
               <dtl>Thank U,Next</dtl>
				</album>
			</genre>
		</songdetail>
		<img3/>
		<songdetail songid="SID3">
			<genre genre_name="rap" genre_id="rap1">
				<songname>Rap Devil</songname>
				<genrename>
               Genre:
               <dtl>Rap</dtl>
				</genrename>
				<country>
               Country:
               <dtl>US</dtl>
				</country>
				<directorname>
               Director Name:
               <dtl>Ronny J</dtl>
				</directorname>
				<producer>
               Producer:
               <dtl>Ronny J</dtl>
				</producer>
				<writer>
               Writer:
               <dtl>Richard Baker, Ronald Spence Jr</dtl>
				</writer>
				<singers>
               Singers:
               <dtl>Machine Gun Kelly(MGK)</dtl>
				</singers>
				<releaseyear>
               Release Year:
               <dtl>
						<year>2018/</year>
					</dtl>
				</releaseyear>
				<songlength>
               Song Length:
               <dtl>4:46</dtl>
				</songlength>
				<album>
               Album Name:
               <dtl>Binge</dtl>
				</album>
			</genre>
		</songdetail>
		<img5/>
		<songdetail songid="SID4">
			<genre genre_name="hiphop" genre_id="h1">
				<songname>Sicko Mode</songname>
				<genrename>
               Genre:
               <dtl>Hip Hop</dtl>
				</genrename>
				<country>
               Country:
               <dtl>US</dtl>
				</country>
				<producer>
               Producer:
               <dtl>Tay Keith, Chahayed</dtl>
				</producer>
				<writer>
               Writer:
               <dtl>Aubrey Graham,John Hawkins</dtl>
				</writer>
				<singers>
               Singers:
               <dtl>Travis Scott</dtl>
				</singers>
				<featby>
               Feat By:
               <dtl>Drake</dtl>
				</featby>
				<noofartists>
               No of Artists:
               <dtl>2</dtl>
				</noofartists>
				<releaseyear>
               Release Year:
               <dtl>
						<year>2018/</year>
						<month>8/</month>
						<day>21</day>
					</dtl>
				</releaseyear>
				<songlength>
               Song Length:
               <dtl>5:12</dtl>
				</songlength>
				<album>
               Album Name:
               <dtl>Champion</dtl>
				</album>
			</genre>
		</songdetail>
		<img4/>
		<songdetail songid="SID5">
			<genre genre_name="countrymusic" genre_id="cm1">
				<songname>Down To One</songname>
				<genrename>
               Genre:
               <dtl>Country Music</dtl>
				</genrename>
				<country>
               Country:
               <dtl>US</dtl>
				</country>
				<directorname>
               Director Name:
               <dtl>Micheal Monnaco</dtl>
				</directorname>
				<producer>
               Producer:
               <dtl>Jody Stevens, Jeff Stevens</dtl>
				</producer>
				<writer>
               Writer:
               <dtl>Justin Ebach, Kyle Fishman</dtl>
				</writer>
				<singers>
               Singers:
               <dtl>Luke Bryan</dtl>
				</singers>
				<featby>
               Feat By:
               <dtl/>
				</featby>
				<releaseyear>
               Release Year:
               <dtl>
						<year>2020/</year>
					</dtl>
				</releaseyear>
				<songlength>
               Song Length:
               <dtl>3:41</dtl>
				</songlength>
				<album>
               Album Name:
               <dtl>One Magarita</dtl>
				</album>
			</genre>
		</songdetail>
		<img6/>
		<songdetail songid="SID6">
			<genre genre_name="rock" genre_id="r1">
				<songname>Guns N Roses</songname>
				<genrename>
               Genre:
               <dtl>Rock</dtl>
				</genrename>
				<country>
               Country:
               <dtl>US</dtl>
				</country>
				<directorname>
               Director Name:
               <dtl>Stephane Sednaoui</dtl>
				</directorname>
				<producer>
               Producer:
               <dtl>Mike Clink</dtl>
				</producer>
				<writer>2
               Writer:
               <dtl>Guns'N Roses</dtl>
				</writer>
				<singers>
               Singers:
               <dtl>Guns'N Roses</dtl>
				</singers>
				<featby>
               Feat By:
               <dtl/>
				</featby>
				<noofartists>
               No of Artists:
               <dtl>5</dtl>
				</noofartists>
				<releaseyear>
               Release Year:
               <dtl>
						<year>1998/</year>
						<month>06/</month>
						<day>21</day>
					</dtl>
				</releaseyear>
				<songlength>
               Song Length:
               <dtl>5:55</dtl>
				</songlength>
				<album>
               Album Name:
               <dtl>Welcome To the jungle</dtl>
				</album>
			</genre>
		</songdetail>
		<img7/>
		<songdetail songid="SID7">
			<genre genre_name="pop" genre_id="p1">
				<songname>Yummy</songname>
				<genrename>
               Genre:
               <dtl>Pop</dtl>
				</genrename>
				<country>
               Country:
               <dtl>Canada</dtl>
				</country>
				<directorname>
               Director Name:
               <dtl>Mike Rikd</dtl>
				</directorname>
				<producer>
               Producer:
               <dtl>Kid Culture, Sasha Sirota</dtl>
				</producer>
				<writer>
               Writer:
               <dtl>Ashley Boyd, Jason Boyd</dtl>
				</writer>
				<singers>
               Singers:
               <dtl>Justin Bieber</dtl>
				</singers>
		<featby>
               Feat By:
               <dtl/>
				</featby>
				<releaseyear>
               Release Year:
               <dtl>
						<year>2020/</year>
						<month>03/</month>
						<day>3</day>
					</dtl>
				</releaseyear>
				<songlength>
               Song Length:
               <dtl>3:30</dtl>
				</songlength>
				<album>
               Album Name:
               <dtl>10,000 Hours</dtl>
				</album>
			</genre>
		</songdetail>
	</songs>
	<contact c_id="CO1">
		<link/>
		<address ad="AO1">
         ADDRESS:
         <con>Balaju,KTM,Nepal</con>
		</address>
		<telephonenumber tel_phone="t1">
         CONTACT US:
         <telephoneno1 tel_id="ti1">9843662374</telephoneno1>
			<telephoneno2 tel_id="ti2">9858237489</telephoneno2>
			<telephoneno3 tel_id="ti3">9806242634</telephoneno3>
			<telephoneno4/>
		</telephonenumber>
		<websiteaddress web="w1">OUR WEBSITE: www.soulsound.com</websiteaddress>
		<note note_id="N1"><![CDATA[Copyright Â© 2016-2021, Soul Sound Private Limited.All Rights Reserved]]></note>
	</contact>
</MusicStore>
